### PR TITLE
Improved performance

### LINKED ISSUE #6: error message when playing the flip sound
Error message: 
image

Potential threads about the error:
- https://github.com/processing/p5.js-sound/issues/506
- https://discourse.processing.org/t/error-when-playing-soundfile/23011
- https://gitmemory.com/issue/processing/p5.js-sound/506/756658958

### LINKED ISSUE #27: Improve site performance
Inspect lighthouse metrics when running lighthouse through F12:

current metrics overview:
image

**Goal**:
Get as high of a score as possible

### PR DESCRIPTION
**Pull request by sentouki**
- moved all <script> tag from head to the end of the body
- replaced p5.js with p5.min.js
- replaced all animal .png with .webp
- added minified version of scripts (minfied with 'JS & CSS Minifier (Minify)', VS Code extension)
- resolves #27

### CODE REVIEW

**Comment by timii** [comment]
How much smaller are the minified Files compared to the original Files and how much smaller are Image Sizes of the .webp Images compared to the .png Images?

**Review by timii — APPROVED** [review]
Looks neat! Very nice improvements

**Comment by sentouki** [comment]
> How much smaller are the minified Files compared to the original Files and how much smaller are Image Sizes of the .webp Images compared to the .png Images?

**images**: from 787kb down to 443kb
**p5js**: from 3699kb down to 796kb
**other scripts**: from 7.44kb to 4.08kb
**css**: from 4.6kb to 3.18kb

overall improvment of 3251.78kb

**Comment by sentouki** [comment]
I forgot to mention that I updated the p5.sound library and it seems like it fixed #6

**Comment by timii** [comment]
> > How much smaller are the minified Files compared to the original Files and how much smaller are Image Sizes of the .webp Images compared to the .png Images?
> 
> **images**: from 787kb down to 443kb
> **p5js**: from 3699kb down to 796kb
> **other scripts**: from 7.44kb to 4.08kb
> **css**: from 4.6kb to 3.18kb
> 
> overall improvment of 3251.78kb

Sounds very good, especially the improvement by replacing the p5 script.

**Comment by timii** [comment]
> I forgot to mention that I updated the p5.sound library and it seems like it fixed #6

Even better. Did you just update it?

**Comment by sentouki** [comment]
yep
p5soundjsupdate
seems like we were using an ancient version of the library

**Pull request merged**
